PROJECT_DETAILS={
    "cv-6631": {
        "slug": "cv-6631",
        "code": "CV-6631",
        "title": "B2B Marketplace for Construction Materials",
        "tagline": "Digital procurement rail for mid-size contractors with transparent pricing and delivery SLAs.",
        "alignment_score": 91,
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "sector": "Construction Tech / B2B Commerce",
        "stage": "Supplier relationships established",
        "founder_commitment": "Full-Time",
        "capital_status": "Bootstrapped",
        "target_raise": "SAR 1.8M pre-seed",
        "runway": "11 months",
        "positions_needed": [
            "Technical Co-Founder (Marketplace Architecture)",
            "Founding Product Manager",
        ],
        "skills_needed": [
            "B2B ordering workflows",
            "Supplier pricing engines",
            "ERP integrations",
            "Dispatch optimization",
        ],
        "overview": "The venture is building a vertical marketplace connecting contractors with vetted material suppliers. The MVP handles RFQs, quote comparisons, payment reconciliation, and delivery tracking for bulk orders.",
        "problem_points": [
            "Procurement decisions still happen via fragmented WhatsApp threads and phone calls.",
            "Contractors face non-transparent pricing and frequent delivery uncertainty.",
            "Supplier discovery for non-core categories remains relationship-driven, not data-driven.",
        ],
        "solution_points": [
            "Standardized RFQ intake with side-by-side quote normalization.",
            "Supplier reliability score based on on-time delivery and quality dispute ratio.",
            "Order timeline tracking with milestone alerts to procurement leads.",
        ],
        "market_assumptions": [
            {"label": "Initial SAM (Central + Eastern KSA)", "value": "SAR 2.4B annual addressed volume"},
            {"label": "Take rate target (Year 2)", "value": "3.1% blended"},
            {"label": "Target contractor accounts (18 months)", "value": "220 active accounts"},
        ],
        "unit_economics": [
            {"metric": "Average order value", "value": "SAR 38,500", "note": "Weighted across cement, steel, finishing"},
            {"metric": "Gross contribution/order", "value": "SAR 1,170", "note": "After payment and logistics fees"},
            {"metric": "Payback period", "value": "3.4 months", "note": "On paid channel cohorts"},
        ],
        "go_to_market": [
            "Founder-led sales to 30 anchor contractors with recurring monthly procurement needs.",
            "Supplier onboarding incentives tied to first 90-day fulfillment quality.",
            "Partnership pipeline with quantity surveyor networks for warm project-intent signals.",
        ],
        "milestones": [
            {"name": "Pilot with 12 contractors", "status": "Completed", "date": "2026-01"},
            {"name": "Supplier scoring engine v1", "status": "In Progress", "date": "2026-04"},
            {"name": "Escrow and milestone payments", "status": "Planned", "date": "2026-06"},
        ],
        "risk_register": [
            {"risk": "Supplier churn during first 2 quarters", "mitigation": "Dual-sourcing per category + SLA rebates", "owner": "Operations"},
            {"risk": "Price parity disputes with offline channels", "mitigation": "Transparent fee model and preferred-volume tiers", "owner": "Commercial"},
            {"risk": "High-touch support load at launch", "mitigation": "Assisted onboarding playbook and in-app guided RFQ", "owner": "Product"},
        ],
        "diligence_docs": [
            "Pilot cohort order logs (anonymized)",
            "Supplier contracts and SLA schedule",
            "Procurement workflow map and support SOP",
            "Financial model v3.2 with sensitivity scenarios",
        ],
    },
    "cv-7784": {
        "slug": "cv-7784",
        "code": "CV-7784",
        "title": "Women-Only Fitness Studio (Riyadh)",
        "tagline": "Premium neighborhood studio with small-group programming and measurable retention loops.",
        "alignment_score": 87,
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "sector": "Fitness / Consumer Services",
        "stage": "Location shortlisted",
        "founder_commitment": "Full-Time",
        "capital_status": "SAR 250,000 committed",
        "target_raise": "SAR 900,000 seed extension",
        "runway": "14 months",
        "positions_needed": [
            "Business & Operations Partner",
            "Head Coach (Founding Team)",
        ],
        "skills_needed": [
            "Membership analytics",
            "Studio operations",
            "Scheduling systems",
            "Community growth",
        ],
        "overview": "The studio is positioned around evidence-backed training cycles for women in professional age groups. The model combines coach-led classes, onboarding assessments, and retention-focused member journeys.",
        "problem_points": [
            "Overcrowded gyms with inconsistent coaching quality reduce retention.",
            "Generic programming fails to adapt to member goals and schedules.",
            "Member communication is fragmented across social channels and paper schedules.",
        ],
        "solution_points": [
            "Capacity-capped classes with coach-to-member ratio standards.",
            "Goal-based progression tracks with monthly assessment checkpoints.",
            "Centralized app for booking, reminders, and class feedback loops.",
        ],
        "market_assumptions": [
            {"label": "Addressable member base (3km radius)", "value": "11,500 potential members"},
            {"label": "Target occupancy (month 12)", "value": "74% average class fill"},
            {"label": "Projected monthly recurring revenue", "value": "SAR 210,000"},
        ],
        "unit_economics": [
            {"metric": "Average membership ticket", "value": "SAR 690/month", "note": "Blended plan portfolio"},
            {"metric": "Gross margin", "value": "58%", "note": "Post coach payroll and facility costs"},
            {"metric": "Retention at month 6 target", "value": "67%", "note": "Cohort target"},
        ],
        "go_to_market": [
            "Pre-opening waitlist with founder-led community sessions.",
            "Referral ladder with in-club rewards and class credits.",
            "Partnerships with local wellness brands for co-marketing campaigns.",
        ],
        "milestones": [
            {"name": "Lease negotiation and fit-out BOQ", "status": "In Progress", "date": "2026-03"},
            {"name": "Core trainer hiring (4 roles)", "status": "Planned", "date": "2026-05"},
            {"name": "Soft launch with 120 members", "status": "Planned", "date": "2026-07"},
        ],
        "risk_register": [
            {"risk": "Slower-than-expected member conversion", "mitigation": "Free assessment funnel + onboarding calls", "owner": "Growth"},
            {"risk": "Coach attrition in first year", "mitigation": "Comp band review and upskilling pathway", "owner": "People Ops"},
            {"risk": "Peak-hour capacity bottlenecks", "mitigation": "Dynamic timetable and demand-based class additions", "owner": "Operations"},
        ],
        "diligence_docs": [
            "Location shortlist scorecard",
            "Member persona interviews (n=42)",
            "Pricing elasticity analysis",
            "P&L model with conservative/base/aggressive cases",
        ],
    },
    "cv-8093": {
        "slug": "cv-8093",
        "code": "CV-8093",
        "title": "Digital Tender Platform for Contractors",
        "tagline": "Tender lifecycle software for mid-market construction firms with compliance-first workflows.",
        "alignment_score": 90,
        "city": "Dammam",
        "country": "Saudi Arabia",
        "sector": "SaaS / Construction Procurement",
        "stage": "Industry validation complete",
        "founder_commitment": "Full-Time",
        "capital_status": "SAR 100,000 committed",
        "target_raise": "SAR 2.3M pre-seed",
        "runway": "9 months",
        "positions_needed": [
            "Full-Stack Technical Co-Founder",
            "Implementation Lead",
        ],
        "skills_needed": [
            "Workflow engines",
            "Document parsing",
            "Role-based permissions",
            "B2B SaaS onboarding",
        ],
        "overview": "The platform digitizes tender intake, document distribution, vendor communication, and scoring workflows. Focus is on reducing cycle time while creating auditable decision trails.",
        "problem_points": [
            "Tender packets are manually distributed and version control is error-prone.",
            "Decision logs are hard to audit, increasing compliance exposure.",
            "Vendor clarification loops delay bid closure.",
        ],
        "solution_points": [
            "Centralized tender workspace with role-scoped access and version history.",
            "Structured scoring templates with committee-level accountability.",
            "Vendor Q&A module with SLA timers and escalation paths.",
        ],
        "market_assumptions": [
            {"label": "Initial ICP companies", "value": "420 regional contractors"},
            {"label": "Target ACV", "value": "SAR 74,000"},
            {"label": "12-month contracted ARR target", "value": "SAR 1.9M"},
        ],
        "unit_economics": [
            {"metric": "Implementation cycle", "value": "4-6 weeks", "note": "Includes process mapping"},
            {"metric": "Gross margin target", "value": "76%", "note": "At 25+ active accounts"},
            {"metric": "Net revenue retention target", "value": "112%", "note": "Through seat expansion"},
        ],
        "go_to_market": [
            "Direct founder pipeline through procurement and PMO heads.",
            "Proof-of-value pilots for one tender cycle before annual contract.",
            "Implementation templates by vertical (civil, MEP, fit-out).",
        ],
        "milestones": [
            {"name": "MVP workflow engine", "status": "Completed", "date": "2025-12"},
            {"name": "First paid pilot conversion", "status": "In Progress", "date": "2026-04"},
            {"name": "ISO-aligned audit trail module", "status": "Planned", "date": "2026-07"},
        ],
        "risk_register": [
            {"risk": "Long enterprise sales cycles", "mitigation": "Pilot-first pricing and procurement-friendly legal pack", "owner": "Founder"},
            {"risk": "Complex integrations with legacy stacks", "mitigation": "CSV/API hybrid bridge during phase one", "owner": "Engineering"},
            {"risk": "Change resistance from tender committees", "mitigation": "Onsite enablement and stakeholder scorecards", "owner": "Implementation"},
        ],
        "diligence_docs": [
            "Discovery transcripts with procurement leads",
            "MVP architecture and security controls",
            "Sample tender workflow configuration",
            "Pipeline and conversion assumptions workbook",
        ],
    },
    "cv-3314": {
        "slug": "cv-3314",
        "code": "CV-3314",
        "title": "Saudi Specialty Coffee Brand (D2C Model)",
        "tagline": "Specialty beans with subscription-first D2C, selective wholesale, and controlled inventory turns.",
        "alignment_score": 74,
        "city": "Jeddah",
        "country": "Saudi Arabia",
        "sector": "Consumer Brand / Food & Beverage",
        "stage": "Brand and supplier secured",
        "founder_commitment": "Full-Time",
        "capital_status": "SAR 200,000 committed",
        "target_raise": "SAR 1.1M seed",
        "runway": "10 months",
        "positions_needed": [
            "Operations & Supply Chain Partner",
            "Growth Marketing Lead",
        ],
        "skills_needed": [
            "Vendor management",
            "Demand planning",
            "Subscription retention",
            "Unit economics discipline",
        ],
        "overview": "The brand focuses on curated monthly coffee drops and recurring subscriptions. Wholesale is limited to high-fit cafes to protect pricing and operational reliability during scale-up.",
        "problem_points": [
            "Generic mass-market coffee options dominate convenience channels.",
            "Specialty quality is inconsistent across online-first local brands.",
            "Many new coffee brands over-expand SKU count early and hurt cash cycle.",
        ],
        "solution_points": [
            "Focused SKU strategy with seasonal rotations and transparent sourcing.",
            "Subscription cohorts with taste preference mapping and guided onboarding.",
            "Inventory gating and reorder points linked to demand forecasts.",
        ],
        "market_assumptions": [
            {"label": "Target monthly orders by month 12", "value": "2,800 orders"},
            {"label": "Subscription share target", "value": "46% of revenue"},
            {"label": "Wholesale partner target", "value": "28 curated accounts"},
        ],
        "unit_economics": [
            {"metric": "Average order value", "value": "SAR 132", "note": "D2C mix with accessories"},
            {"metric": "Contribution margin", "value": "41%", "note": "After shipping and payment fees"},
            {"metric": "CAC payback", "value": "2.7 months", "note": "Paid social + referral mix"},
        ],
        "go_to_market": [
            "Creator-led tasting sessions and launch drops for early advocates.",
            "Referral mechanics embedded into subscription lifecycle.",
            "Selective cafe placements to strengthen local credibility.",
        ],
        "milestones": [
            {"name": "Roasting partner QA sign-off", "status": "Completed", "date": "2026-02"},
            {"name": "Subscription portal launch", "status": "In Progress", "date": "2026-04"},
            {"name": "Wholesale onboarding playbook", "status": "Planned", "date": "2026-06"},
        ],
        "risk_register": [
            {"risk": "Inventory mismatch for seasonal blends", "mitigation": "Rolling 8-week forecast and SKU throttling", "owner": "Operations"},
            {"risk": "Paid acquisition efficiency volatility", "mitigation": "Cohort-level CAC caps and channel diversification", "owner": "Growth"},
            {"risk": "Fulfillment quality variance", "mitigation": "3PL QA checklist and SLA penalty clauses", "owner": "Founder"},
        ],
        "diligence_docs": [
            "Brand strategy memo and positioning study",
            "Supplier QA and cupping records",
            "Subscription funnel baseline analytics",
            "Cash-flow model with inventory stress tests",
        ],
    },
    "cv-9245": {
        "slug": "cv-9245",
        "code": "CV-9245",
        "title": "Performance Optimization App for GCC Professionals",
        "tagline": "Personal performance stack blending fitness, focus, and habit telemetry for knowledge workers.",
        "alignment_score": 58,
        "city": "Remote-first (GCC)",
        "country": "Saudi Arabia / UAE",
        "sector": "Consumer App / Productivity + Wellness",
        "stage": "UI prototype completed",
        "founder_commitment": "Part-Time moving to Full-Time within 6 months",
        "capital_status": "Self-funded",
        "target_raise": "SAR 1.4M pre-seed",
        "runway": "8 months",
        "positions_needed": [
            "Mobile App Developer (Flutter/React Native)",
            "Data Product Analyst",
        ],
        "skills_needed": [
            "Mobile architecture",
            "Behavioral product loops",
            "API integrations",
            "Analytics instrumentation",
        ],
        "overview": "The app combines activity tracking, calendar context, focus blocks, and self-reported energy markers into one daily score model. The product thesis is sustained routine quality over short-term intensity.",
        "problem_points": [
            "Users juggle multiple disconnected tools for fitness, scheduling, and focus.",
            "Most habit apps optimize streak vanity metrics rather than meaningful outcomes.",
            "Workload and wellness data are rarely interpreted together.",
        ],
        "solution_points": [
            "Unified daily performance dashboard with weighted signals.",
            "Adaptive coaching prompts based on sleep, schedule, and workload variance.",
            "Weekly reflection flow with trend diagnosis and recommended interventions.",
        ],
        "market_assumptions": [
            {"label": "Target free users (12 months)", "value": "28,000"},
            {"label": "Premium conversion target", "value": "4.8%"},
            {"label": "Monthly premium ARPU", "value": "SAR 39"},
        ],
        "unit_economics": [
            {"metric": "Blended CAC target", "value": "SAR 24", "note": "Organic-led with creator partnerships"},
            {"metric": "Month-3 retention target", "value": "33%", "note": "Premium and free combined"},
            {"metric": "Gross margin", "value": "83%", "note": "Excluding R&D payroll"},
        ],
        "go_to_market": [
            "Early access cohort through professional communities and founder circles.",
            "Content-led acquisition around practical performance routines.",
            "Referral unlocks tied to premium feature trials.",
        ],
        "milestones": [
            {"name": "Prototype usability tests (n=55)", "status": "Completed", "date": "2026-02"},
            {"name": "Beta release and instrumentation", "status": "In Progress", "date": "2026-05"},
            {"name": "Subscription launch", "status": "Planned", "date": "2026-08"},
        ],
        "risk_register": [
            {"risk": "Retention volatility after week two", "mitigation": "First-week activation redesign and tailored nudges", "owner": "Product"},
            {"risk": "Data privacy trust concerns", "mitigation": "Clear consent model and privacy dashboard", "owner": "Engineering"},
            {"risk": "Founder bandwidth constraints", "mitigation": "Time-boxed roadmap and fractional support", "owner": "Founder"},
        ],
        "diligence_docs": [
            "Prototype test recordings and UX report",
            "Event taxonomy and analytics plan",
            "Retention benchmark analysis",
            "Roadmap and hiring plan (2 quarters)",
        ],
    },
}