# Generated by Codex on 2026-03-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covise_app", "0003_profile_canonical_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("matched_only", "Matched users only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=20,
                    ),
                ),
                ("show_conviction_score", models.BooleanField(default=True)),
                ("show_cv_to_matches", models.BooleanField(default=True)),
                ("show_linkedin_to_matches", models.BooleanField(default=True)),
                ("appear_in_search", models.BooleanField(default=True)),
                ("pause_matching", models.BooleanField(default=False)),
                ("ai_enabled", models.BooleanField(default=True)),
                ("ai_read_messages", models.BooleanField(default=True)),
                ("ai_read_workspace", models.BooleanField(default=True)),
                ("ai_post_updates", models.BooleanField(default=False)),
                ("ai_send_messages", models.BooleanField(default=False)),
                ("ai_edit_workspace", models.BooleanField(default=False)),
                ("ai_manage_milestones", models.BooleanField(default=False)),
                ("email_new_match", models.BooleanField(default=True)),
                ("email_new_message", models.BooleanField(default=True)),
                ("email_connection_request", models.BooleanField(default=True)),
                ("email_request_accepted", models.BooleanField(default=True)),
                ("email_milestone_reminder", models.BooleanField(default=True)),
                ("email_workspace_activity", models.BooleanField(default=False)),
                ("email_platform_updates", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=False)),
                ("in_app_new_match", models.BooleanField(default=True)),
                ("in_app_new_message", models.BooleanField(default=True)),
                ("in_app_connection_request", models.BooleanField(default=True)),
                ("in_app_request_accepted", models.BooleanField(default=True)),
                ("in_app_milestone_reminder", models.BooleanField(default=True)),
                ("in_app_workspace_activity", models.BooleanField(default=False)),
                ("in_app_platform_updates", models.BooleanField(default=True)),
                ("in_app_marketing", models.BooleanField(default=False)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
