# Generated by Django 6.0.2 on 2026-03-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0003_onboardingresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='cv',
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='capital_contribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='cofounder_commitment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='cofounder_location_pref',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='cofounders_needed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='cohort_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='commitment_level',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='compensation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='current_role',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='customer_count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='execution_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='foreign_industry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='foreign_one_liner',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='foreign_stage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='foreign_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='founder_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='founder_type_preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='funding_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='home_country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='how_heard',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='incubator_looking_for',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='incubator_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='industries_interested',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='industry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investment_geography',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investment_industries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investment_stage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investor_looking_for',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investor_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investor_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='investor_value_add',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='leadership_style',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='local_partner_need',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='looking_for_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='looking_for_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='monthly_revenue',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='one_liner',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='profile_visibility_consent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='program_industries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='program_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='program_offering',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='program_stage_focus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='program_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='referral_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='risk_tolerance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='specialist_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='stage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='target_gcc_market',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='target_market',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='team_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='ticket_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='user_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='venture_stage_preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingresponse',
            name='years_experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='cv_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='waitlist_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='covise_app.waitlistentry'),
        ),
    ]
