# Generated by Codex on 2026-03-20

from django.db import migrations, models


def blank_codes_to_null(apps, schema_editor):
    Profile = apps.get_model("covise_app", "Profile")
    Profile.objects.filter(my_referral_code="").update(my_referral_code=None)


def null_codes_to_blank(apps, schema_editor):
    Profile = apps.get_model("covise_app", "Profile")
    Profile.objects.filter(my_referral_code__isnull=True).update(my_referral_code="")


class Migration(migrations.Migration):

    dependencies = [
        ("covise_app", "0004_userpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="my_referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(blank_codes_to_null, null_codes_to_blank),
    ]
