# Generated by Django 6.0.2 on 2026-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0004_remove_waitlistentry_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
