# Generated by Django 6.0.2 on 2026-03-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0005_alter_waitlistentry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='my_referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='covise_app.waitlistentry'),
        ),
    ]
