# Generated by Django 6.0.2 on 2026-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0008_waitlistentry_referral_code_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_visibility_consent',
        ),
    ]
