# Generated by Django 6.0.2 on 2026-03-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0010_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
