# Generated by Django 6.0.2 on 2026-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0011_post_comments_number_post_likes_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
