# Generated by Django 6.0.2 on 2026-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0014_active_projects_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_projects',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
