# Generated by Django 6.0.2 on 2026-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0015_active_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=400)),
                ('founder_name', models.CharField(blank=True, max_length=150)),
                ('founder_initials', models.CharField(blank=True, max_length=4)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(blank=True, max_length=200)),
                ('founder_commitment', models.CharField(blank=True, max_length=100)),
                ('capital_status', models.CharField(blank=True, max_length=150)),
                ('target_raise', models.CharField(blank=True, max_length=150)),
                ('runway', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('card_description', models.TextField(blank=True)),
                ('alignment_score', models.PositiveIntegerField(default=0)),
                ('alignment_details', models.JSONField(blank=True, default=dict)),
                ('positions_needed', models.JSONField(blank=True, default=list)),
                ('skills_needed', models.JSONField(blank=True, default=list)),
                ('problem_points', models.JSONField(blank=True, default=list)),
                ('solution_points', models.JSONField(blank=True, default=list)),
                ('market_assumptions', models.JSONField(blank=True, default=list)),
                ('unit_economics', models.JSONField(blank=True, default=list)),
                ('go_to_market', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('risk_register', models.JSONField(blank=True, default=list)),
                ('diligence_docs', models.JSONField(blank=True, default=list)),
                ('filter_tokens', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True)),
                ('team_members_filled', models.PositiveIntegerField(default=1)),
                ('team_size_target', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_notes', models.TextField(blank=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
    ]
