# Generated by Django 6.0.2 on 2026-03-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0017_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_interactive_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_in_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
