# Generated by Django 6.0.2 on 2026-04-10 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0020_conversationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='custom_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='no_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='venture_summary',
            field=models.TextField(blank=True),
        ),
    ]
