# Generated by Django 6.0.2 on 2026-04-10 15:17

import uuid
from django.db import migrations, models


WAITLIST_EMAIL_VERIFICATION_SQL = """
CREATE TABLE IF NOT EXISTS covise_app_waitlistemailverification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    token uuid NOT NULL,
    verification_code varchar(6) NOT NULL DEFAULT '',
    verified_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE covise_app_waitlistemailverification
    ADD COLUMN IF NOT EXISTS email varchar(254),
    ADD COLUMN IF NOT EXISTS token uuid,
    ADD COLUMN IF NOT EXISTS verification_code varchar(6) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS verified_at timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS covise_app_waitlistemailverification_email_key
    ON covise_app_waitlistemailverification (email);
CREATE UNIQUE INDEX IF NOT EXISTS covise_app_waitlistemailverification_token_key
    ON covise_app_waitlistemailverification (token);
"""


WAITLIST_ENTRY_COLUMNS_SQL = """
ALTER TABLE covise_app_waitlistentry
    ADD COLUMN IF NOT EXISTS custom_description varchar(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description varchar(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS no_linkedin boolean NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS referral_code varchar(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS venture_summary text NOT NULL DEFAULT '';
ALTER TABLE covise_app_waitlistentry
    ALTER COLUMN custom_description DROP DEFAULT,
    ALTER COLUMN description DROP DEFAULT,
    ALTER COLUMN no_linkedin DROP DEFAULT,
    ALTER COLUMN referral_code DROP DEFAULT,
    ALTER COLUMN venture_summary DROP DEFAULT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("covise_app", "0020_conversationrequest"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=WAITLIST_EMAIL_VERIFICATION_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="WaitlistEmailVerification",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("email", models.EmailField(max_length=254, unique=True)),
                        (
                            "token",
                            models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                        ),
                        ("verification_code", models.CharField(blank=True, max_length=6)),
                        ("verified_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=WAITLIST_ENTRY_COLUMNS_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="waitlistentry",
                    name="custom_description",
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name="waitlistentry",
                    name="description",
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name="waitlistentry",
                    name="no_linkedin",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="waitlistentry",
                    name="referral_code",
                    field=models.CharField(blank=True, max_length=20),
                ),
                migrations.AddField(
                    model_name="waitlistentry",
                    name="venture_summary",
                    field=models.TextField(blank=True),
                ),
            ],
        ),
    ]
