# Generated by Django 6.0.2 on 2026-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0021_waitlistemailverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
