# Generated by Django 6.0.2 on 2026-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covise_app", "0022_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="theme_color",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("blue", "Blue"),
                    ("amber", "Amber"),
                    ("green", "Green"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
