# Generated by Django 6.0.2 on 2026-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covise_app", "0023_post_theme_color_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="theme_color",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("blue", "Blue"),
                    ("amber", "Amber"),
                    ("green", "Green"),
                    ("red", "Red"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
