# Generated by Django 6.0.2 on 2026-04-19 20:17

import covise_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0042_profile_network_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New message'), ('conversation_request', 'Conversation request'), ('request_accepted', 'Request accepted'), ('post_mention', 'Post mention'), ('new_post', 'New post')], max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=covise_app.storage.PostImageStorage(), upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=covise_app.storage.PostImageStorage(), upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=covise_app.storage.PostImageStorage(), upload_to='profile_images/'),
        ),
    ]
