# Generated by Django 6.0.2 on 2026-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covise_app', '0046_post_quote_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='date',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
